config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'

  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'
  patch 'tasks/:id', to: 'tasks#update'


  get '/tasks/:id', to: 'tasks#show', as: 'task'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    # @tasks.find(params[:id])
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    completion_info = params[:task][:completed]
    completion_check(completion_info) if completion_info.present?

    @task.update(task_params)
    redirection(params[:redirection])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def completion_check(params)
    # fixing checkbox values to true or false for rails usage
    case params.to_i
    when 0
      params = false
    when 1
      params = true
    end
    params
  end

  def redirection(params = nil)
    # checking if different redirection is needed based on
    # information from the form
    if params.present?
      redirect_to tasks_path
    else
      redirect_to task_path(@task)
    end
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
  <li>
    <label class="container">
      <!-- Looping over the tasks to create interative checkbox -->

      <%= form_for task, url: task_path(task.id), action: "update" do |f| %>
        <!-- javascript code to submit when clicking on checkbox -->
        <% js_code = "document.getElementById('edit_task_#{task.id}').submit();" %>
        <%= f.check_box(:completed, onchange: js_code) %>
        <%= link_to "#{task.title}", task_path(task.id) %>
        <!-- field tag to pass information about the redirection after submit -->
        <%= hidden_field_tag 'redirection', 'home' %>
        <%= f.submit "Done", id: 'hidden' %>
      <% end %>

    </label>
  </li>
  <% end %>
</ul>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title  %></h1>
<p><%= @task.details  %></p>

<% status = "Completed" if @task.completed %>
<% status = "Not completed" unless @task.completed %>

<%= form_for @task, url: {action: "update"} do |f| %>
  <!-- javascript code to submit when clicking on checkbox -->
  <% js_code = "document.querySelector('.edit_task').submit();" %>
  <%= f.check_box(:completed, onchange: js_code) %>
  <%= f.label(:completed, "#{status}") %>
  <%= f.submit "Done", id: 'hidden' %>
<% end %>


<%= link_to "List all", tasks_path %>
<%= link_to "Edit", tasks_edit_path %>
<%= link_to "Delete",  task_path(@task), method: :delete, data: { confirm: "Are you sure?" }%>